# Drivers

In [1]:
import requests
import pandas as pd

In [2]:
# format is race number_language
# race 5 = canada
url = "https://fantasy.formula1.com/feeds/drivers/5_en.json"

r = requests.get(url)

print(r.status_code)

200

In [3]:
data = r.json()

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['Data', 'Meta'])

In [4]:
# dumping the json before dataframe changes
import os
import json

In [6]:
race_number = 5

In [7]:
save_path = os.path.join("..", "..", "data", "raw")

with open(f"{save_path}/assets_race_{race_number}.json", "w") as f:
    json.dump(data, f, indent=2)

In [8]:
print(os.getcwd())

/Users/miranda/code/knightmm/f1-fantasy-analytics/notebooks/exploratory

In [9]:
print(type(data["Data"]))

<class 'dict'>

In [10]:
print(data["Data"].keys())

dict_keys(['Value', 'FeedTime'])

In [11]:
values = data["Data"]["Value"]

In [14]:
print(type(values))
print(len(values))
print(values[0])

<class 'list'>
33
{'PlayerId': '18', 'Skill': 1, 'PositionName': 'DRIVER', 'Value': 12.8, 'TeamId': '23', 'FUllName': 'Pierre Gasly', 'DisplayName': 'P. Gasly', 'TeamName': 'Alpine', 'Status': '0', 'IsActive': '1', 'DriverTLA': 'GAS', 'DriverReference': 'PIEGAS01', 'CountryName': 'Rouen, France', 'OverallPpints': '37.00', 'GamedayPoints': '0', 'SelectedPercentage': '19', 'CaptainSelectedPercentage': '1', 'OldPlayerValue': 13.0, 'BestRaceFinished': '6', 'HigestGridStart': '7', 'HigestChampFinish': '', 'FastestPitstopAward': '', 'BestRaceFinishCount': 1, 'HighestGridStartCount': 1, 'HighestChampFinishCount': 0, 'FastestPitstopAwardCount': 0, 'QualifyingPoints': '', 'RacePoints': '', 'SprintPoints': '', 'NoNegativePoints': '', 'F1PlayerId': '8', 'FirstName': 'Pierre', 'LastName': 'Gasly', 'SessionWisePoints': [{'sessionnumber': 1, 'sessiontype': 'Sprint Qualifying', 'points': None, 'nonegative_points': None}, {'sessionnumber': 2, 'sessiontype': 'Qualifying', 'points': None, 'nonegative_points': None}, {'sessionnumber': 3, 'sessiontype': 'Race', 'points': None, 'nonegative_points': None}], 'AdditionalStats': {'fastest_lap_pts': 0.0, 'dotd_pts': 0.0, 'overtaking_pts': 28.0, 'q3_finishes_pts': 10.0, 'top10_race_position_pts': 15.0, 'top8_sprint_position_pts': 1.0, 'total_position_pts': 26.0, 'total_position_gained_lost': 3.0, 'total_dnf_dq_pts': -20.0, 'value_for_money': 0.72}, 'old_Value': 0.0, 'new_value': 0.0, 'ProjectedGamedayPoints': '0', 'ProjectedNoNegativePoints': '0', 'ProjectedOverallPpints': '37.00'}

In [15]:
# normalizing only the data in the values subdictionary
df = pd.json_normalize(values)

df.head()

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
0,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,0,1,...,0.0,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72
1,11059,1,DRIVER,8.2,23,Franco Colapinto,F. Colapinto,Alpine,0,1,...,0.0,0.0,27.0,3.0,7.0,0.0,10.0,4.0,0.0,1.25
2,12,1,DRIVER,8.0,24,Fernando Alonso,F. Alonso,Aston Martin,0,1,...,0.0,0.0,32.0,0.0,0.0,0.0,0.0,11.0,-40.0,0.09
3,129,1,DRIVER,5.6,24,Lance Stroll,L. Stroll,Aston Martin,0,1,...,0.0,0.0,22.0,0.0,0.0,0.0,0.0,6.0,-65.0,-1.65
4,11051,1,DRIVER,5.2,2640,Gabriel Bortoleto,G. Bortoleto,Audi,0,1,...,0.0,0.0,27.0,3.0,2.0,0.0,5.0,7.0,-30.0,0.43

In [16]:
df.shape

(33, 49)

In [17]:
df.columns.tolist()

['PlayerId',
 'Skill',
 'PositionName',
 'Value',
 'TeamId',
 'FUllName',
 'DisplayName',
 'TeamName',
 'Status',
 'IsActive',
 'DriverTLA',
 'DriverReference',
 'CountryName',
 'OverallPpints',
 'GamedayPoints',
 'SelectedPercentage',
 'CaptainSelectedPercentage',
 'OldPlayerValue',
 'BestRaceFinished',
 'HigestGridStart',
 'HigestChampFinish',
 'FastestPitstopAward',
 'BestRaceFinishCount',
 'HighestGridStartCount',
 'HighestChampFinishCount',
 'FastestPitstopAwardCount',
 'QualifyingPoints',
 'RacePoints',
 'SprintPoints',
 'NoNegativePoints',
 'F1PlayerId',
 'FirstName',
 'LastName',
 'SessionWisePoints',
 'old_Value',
 'new_value',
 'ProjectedGamedayPoints',
 'ProjectedNoNegativePoints',
 'ProjectedOverallPpints',
 'AdditionalStats.fastest_lap_pts',
 'AdditionalStats.dotd_pts',
 'AdditionalStats.overtaking_pts',
 'AdditionalStats.q3_finishes_pts',
 'AdditionalStats.top10_race_position_pts',
 'AdditionalStats.top8_sprint_position_pts',
 'AdditionalStats.total_position_pts',
 'AdditionalStats.total_position_gained_lost',
 'AdditionalStats.total_dnf_dq_pts',
 'AdditionalStats.value_for_money']

In [18]:
df[df["PlayerId"] == "118"]

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
10,118,1,DRIVER,9.7,26,Esteban Ocon,E. Ocon,Haas F1 Team,0,1,...,0.0,0.0,44.0,0.0,1.0,0.0,1.0,11.0,0.0,1.44

In [19]:
# experimenting with flattening the entire json in order to keep feedtime metadata
pd.json_normalize(data)

,Data.Value,Data.FeedTime.UTCTime,Data.FeedTime.ISTTime,Data.FeedTime.CESTTime,Meta.Message,Meta.RetVal,Meta.Success,Meta.Timestamp.UTCTime,Meta.Timestamp.ISTTime,Meta.Timestamp.CESTTime,Meta.StatusCode,Meta.Maintenance
0,"[{'PlayerId': '18', 'Skill': 1, 'PositionName'...",5/19/2026 3:14:29 PM,5/19/2026 8:44:29 PM,5/19/2026 5:14:29 PM,Success,1,True,5/19/2026 3:14:29 PM,5/19/2026 8:44:29 PM,5/19/2026 5:14:29 PM,200,

In [20]:
pd.DataFrame([data["Data"]["FeedTime"]])

                UTCTime               ISTTime              CESTTime
0  5/19/2026 3:14:29 PM  5/19/2026 8:44:29 PM  5/19/2026 5:14:29 PM

In [21]:
# appending the API feed timestamp to the dataframe containing asset data
df["feed_time_utc"] = data["Data"]["FeedTime"]["UTCTime"]

In [22]:
df.head(2)

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money,feed_time_utc
0,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,0,1,...,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72,5/19/2026 3:14:29 PM
1,11059,1,DRIVER,8.2,23,Franco Colapinto,F. Colapinto,Alpine,0,1,...,0.0,27.0,3.0,7.0,0.0,10.0,4.0,0.0,1.25,5/19/2026 3:14:29 PM

In [23]:
# extracting the race number from the URL used to fetch data
import re

race_number = re.search(r"drivers/(\d+)_", url).group(1)
race_number

'5'

In [24]:
#appending the race number to the dataframe
df["race_number"] = race_number
df.head(2)

,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,Status,IsActive,...,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money,feed_time_utc,race_number
0,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,0,1,...,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72,5/19/2026 3:14:29 PM,5
1,11059,1,DRIVER,8.2,23,Franco Colapinto,F. Colapinto,Alpine,0,1,...,27.0,3.0,7.0,0.0,10.0,4.0,0.0,1.25,5/19/2026 3:14:29 PM,5

In [25]:
cols_to_front = ["race_number", "feed_time_utc"]
remaining_cols = [col for col in df.columns if col not in cols_to_front]

df = df[cols_to_front + remaining_cols]
df.head(1)

,race_number,feed_time_utc,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
0,5,5/19/2026 3:14:29 PM,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,...,0.0,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72

In [35]:
df["race_number"] = df["race_number"].astype(int)
df["feed_time_utc"] = pd.to_datetime(df["feed_time_utc"], format="%m/%d/%Y %I:%M:%S %p", utc=True)
df.head(1)

,race_number,feed_time_utc,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
0,5,2026-05-19 15:14:29+00:00,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,...,0.0,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72

In [37]:
df.dtypes

race_number                                                 int64
feed_time_utc                                 datetime64[ns, UTC]
PlayerId                                                   object
Skill                                                       int64
PositionName                                               object
Value                                                     float64
TeamId                                                     object
FUllName                                                   object
DisplayName                                                object
TeamName                                                   object
Status                                                     object
IsActive                                                   object
DriverTLA                                                  object
DriverReference                                            object
CountryName                                                object
OverallPpints                                              object
GamedayPoints                                              object
SelectedPercentage                                         object
CaptainSelectedPercentage                                  object
OldPlayerValue                                            float64
BestRaceFinished                                           object
HigestGridStart                                            object
HigestChampFinish                                          object
FastestPitstopAward                                        object
BestRaceFinishCount                                         int64
HighestGridStartCount                                       int64
HighestChampFinishCount                                     int64
FastestPitstopAwardCount                                    int64
QualifyingPoints                                           object
RacePoints                                                 object
SprintPoints                                               object
NoNegativePoints                                           object
F1PlayerId                                                 object
FirstName                                                  object
LastName                                                   object
SessionWisePoints                                          object
old_Value                                                 float64
new_value                                                 float64
ProjectedGamedayPoints                                     object
ProjectedNoNegativePoints                                  object
ProjectedOverallPpints                                     object
AdditionalStats.fastest_lap_pts                           float64
AdditionalStats.dotd_pts                                  float64
AdditionalStats.overtaking_pts                            float64
AdditionalStats.q3_finishes_pts                           float64
AdditionalStats.top10_race_position_pts                   float64
AdditionalStats.top8_sprint_position_pts                  float64
AdditionalStats.total_position_pts                        float64
AdditionalStats.total_position_gained_lost                float64
AdditionalStats.total_dnf_dq_pts                          float64
AdditionalStats.value_for_money                           float64
dtype: object

In [43]:
df.columns

Index(['race_number', 'feed_time_utc', 'PlayerId', 'Skill', 'PositionName',
       'Value', 'TeamId', 'FUllName', 'DisplayName', 'TeamName', 'Status',
       'IsActive', 'DriverTLA', 'DriverReference', 'CountryName',
       'OverallPpints', 'GamedayPoints', 'SelectedPercentage',
       'CaptainSelectedPercentage', 'OldPlayerValue', 'BestRaceFinished',
       'HigestGridStart', 'HigestChampFinish', 'FastestPitstopAward',
       'BestRaceFinishCount', 'HighestGridStartCount',
       'HighestChampFinishCount', 'FastestPitstopAwardCount',
       'QualifyingPoints', 'RacePoints', 'SprintPoints', 'NoNegativePoints',
       'F1PlayerId', 'FirstName', 'LastName', 'SessionWisePoints', 'old_Value',
       'new_value', 'ProjectedGamedayPoints', 'ProjectedNoNegativePoints',
       'ProjectedOverallPpints', 'AdditionalStats.fastest_lap_pts',
       'AdditionalStats.dotd_pts', 'AdditionalStats.overtaking_pts',
       'AdditionalStats.q3_finishes_pts',
       'AdditionalStats.top10_race_position_pts',
       'AdditionalStats.top8_sprint_position_pts',
       'AdditionalStats.total_position_pts',
       'AdditionalStats.total_position_gained_lost',
       'AdditionalStats.total_dnf_dq_pts', 'AdditionalStats.value_for_money'],
      dtype='object')

In [ ]:
numeric_cols = ['Value', 'OverallPpints', 'GamedayPoints', 'SelectedPercentage', 
       'CaptainSelectedPercentage', 'OldPlayerValue', 'BestRaceFinished', 
       'HigestGridStart', 'HigestChampFinish', 'FastestPitstopAward',
       'BestRaceFinishCount', 'HighestGridStartCount',
       'HighestChampFinishCount', 'FastestPitstopAwardCount',
       'QualifyingPoints', 'RacePoints', 'SprintPoints', 'NoNegativePoints', 'old_Value',
       'new_value', 'ProjectedGamedayPoints', 'ProjectedNoNegativePoints',
       'ProjectedOverallPpints', 'AdditionalStats.fastest_lap_pts',
       'AdditionalStats.dotd_pts', 'AdditionalStats.overtaking_pts',
       'AdditionalStats.q3_finishes_pts',
       'AdditionalStats.top10_race_position_pts',
       'AdditionalStats.top8_sprint_position_pts',
       'AdditionalStats.total_position_pts',
       'AdditionalStats.total_position_gained_lost',
       'AdditionalStats.total_dnf_dq_pts', 'AdditionalStats.value_for_money']

In [ ]:
int_cols = [
    "GamedayPoints",
    "BestRaceFinished",
    "HigestGridStart",
    "BestRaceFinishCount",
    "HighestGridStartCount",
    "HighestChampFinishCount",
    "FastestPitstopAwardCount",
]

float_cols = [
    "Value",
    "OverallPpints",
    "QualifyingPoints",
    "RacePoints",
    "SprintPoints",
    "NoNegativePoints",
    "ProjectedGamedayPoints",
    "ProjectedNoNegativePoints",
    "ProjectedOverallPpints",
    "SelectedPercentage",
    "CaptainSelectedPercentage",
    "OldPlayerValue",
    "FastestPitstopAward",
    "old_Value",
    "new_value",
    "HigestChampFinish",
]

In [ ]:
for col in int_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

for col in float_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [45]:
df.dtypes

race_number                                                 int64
feed_time_utc                                 datetime64[ns, UTC]
PlayerId                                                   object
Skill                                                       int64
PositionName                                               object
Value                                                     float64
TeamId                                                     object
FUllName                                                   object
DisplayName                                                object
TeamName                                                   object
Status                                                     object
IsActive                                                   object
DriverTLA                                                  object
DriverReference                                            object
CountryName                                                object
OverallPpints                                             float64
GamedayPoints                                               int64
SelectedPercentage                                          int64
CaptainSelectedPercentage                                   int64
OldPlayerValue                                            float64
BestRaceFinished                                            int64
HigestGridStart                                             int64
HigestChampFinish                                         float64
FastestPitstopAward                                       float64
BestRaceFinishCount                                         int64
HighestGridStartCount                                       int64
HighestChampFinishCount                                     int64
FastestPitstopAwardCount                                    int64
QualifyingPoints                                          float64
RacePoints                                                float64
SprintPoints                                              float64
NoNegativePoints                                          float64
F1PlayerId                                                 object
FirstName                                                  object
LastName                                                   object
SessionWisePoints                                          object
old_Value                                                 float64
new_value                                                 float64
ProjectedGamedayPoints                                      int64
ProjectedNoNegativePoints                                   int64
ProjectedOverallPpints                                    float64
AdditionalStats.fastest_lap_pts                           float64
AdditionalStats.dotd_pts                                  float64
AdditionalStats.overtaking_pts                            float64
AdditionalStats.q3_finishes_pts                           float64
AdditionalStats.top10_race_position_pts                   float64
AdditionalStats.top8_sprint_position_pts                  float64
AdditionalStats.total_position_pts                        float64
AdditionalStats.total_position_gained_lost                float64
AdditionalStats.total_dnf_dq_pts                          float64
AdditionalStats.value_for_money                           float64
dtype: object

In [ ]:
# separating drivers and constructors
constructor_filter = df["PositionName"] == "CONSTRUCTOR"
constructors_df = df[constructor_filter].copy()
constructors_df.head(2)

,race_number,feed_time_utc,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
22,5,2026-05-19 15:14:29+00:00,28,2,CONSTRUCTOR,30.5,28,Mercedes,Mercedes,,...,20.0,0.0,68.0,73.0,160.0,20.0,253.0,-6.0,0.0,3.34
23,5,2026-05-19 15:14:29+00:00,29,2,CONSTRUCTOR,29.2,29,Red Bull Racing,Red Bull Racing,,...,10.0,0.0,109.0,25.0,26.0,4.0,55.0,5.0,-75.0,1.22

In [30]:
constructors_df.columns

Index(['race_number', 'feed_time_utc', 'PlayerId', 'Skill', 'PositionName',
       'Value', 'TeamId', 'FUllName', 'DisplayName', 'TeamName', 'Status',
       'IsActive', 'DriverTLA', 'DriverReference', 'CountryName',
       'OverallPpints', 'GamedayPoints', 'SelectedPercentage',
       'CaptainSelectedPercentage', 'OldPlayerValue', 'BestRaceFinished',
       'HigestGridStart', 'HigestChampFinish', 'FastestPitstopAward',
       'BestRaceFinishCount', 'HighestGridStartCount',
       'HighestChampFinishCount', 'FastestPitstopAwardCount',
       'QualifyingPoints', 'RacePoints', 'SprintPoints', 'NoNegativePoints',
       'F1PlayerId', 'FirstName', 'LastName', 'SessionWisePoints', 'old_Value',
       'new_value', 'ProjectedGamedayPoints', 'ProjectedNoNegativePoints',
       'ProjectedOverallPpints', 'AdditionalStats.fastest_lap_pts',
       'AdditionalStats.dotd_pts', 'AdditionalStats.overtaking_pts',
       'AdditionalStats.q3_finishes_pts',
       'AdditionalStats.top10_race_position_pts',
       'AdditionalStats.top8_sprint_position_pts',
       'AdditionalStats.total_position_pts',
       'AdditionalStats.total_position_gained_lost',
       'AdditionalStats.total_dnf_dq_pts', 'AdditionalStats.value_for_money'],
      dtype='object')

In [31]:
# empty strings "" are not considered to be be na so all columns are considered populated
constructors_df.isna().sum().sort_values(ascending=False)

race_number                                   0
ProjectedGamedayPoints                        0
QualifyingPoints                              0
RacePoints                                    0
SprintPoints                                  0
NoNegativePoints                              0
F1PlayerId                                    0
FirstName                                     0
LastName                                      0
SessionWisePoints                             0
old_Value                                     0
new_value                                     0
ProjectedNoNegativePoints                     0
HighestChampFinishCount                       0
ProjectedOverallPpints                        0
AdditionalStats.fastest_lap_pts               0
AdditionalStats.dotd_pts                      0
AdditionalStats.overtaking_pts                0
AdditionalStats.q3_finishes_pts               0
AdditionalStats.top10_race_position_pts       0
AdditionalStats.top8_sprint_position_pts      0
AdditionalStats.total_position_pts            0
AdditionalStats.total_position_gained_lost    0
AdditionalStats.total_dnf_dq_pts              0
FastestPitstopAwardCount                      0
HighestGridStartCount                         0
feed_time_utc                                 0
DriverTLA                                     0
PlayerId                                      0
Skill                                         0
PositionName                                  0
Value                                         0
TeamId                                        0
FUllName                                      0
DisplayName                                   0
TeamName                                      0
Status                                        0
IsActive                                      0
DriverReference                               0
BestRaceFinishCount                           0
CountryName                                   0
OverallPpints                                 0
GamedayPoints                                 0
SelectedPercentage                            0
CaptainSelectedPercentage                     0
OldPlayerValue                                0
BestRaceFinished                              0
HigestGridStart                               0
HigestChampFinish                             0
FastestPitstopAward                           0
AdditionalStats.value_for_money               0
dtype: int64

In [32]:
constructors_df.columns[(constructors_df == "").all()]

Index(['TeamName', 'Status', 'DriverReference', 'CountryName',
       'HigestChampFinish', 'FastestPitstopAward', 'QualifyingPoints',
       'RacePoints', 'SprintPoints', 'NoNegativePoints'],
      dtype='object')

In [33]:
constructor_drop_cols = ['TeamName', 'Status', 'DriverReference', 'CountryName']
constructors_df = constructors_df.drop(columns=constructor_drop_cols)
constructors_df.head(1)

,race_number,feed_time_utc,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,IsActive,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
22,5,2026-05-19 15:14:29+00:00,28,2,CONSTRUCTOR,30.5,28,Mercedes,Mercedes,1,...,20.0,0.0,68.0,73.0,160.0,20.0,253.0,-6.0,0.0,3.34

In [34]:
constructors_df.dtypes

race_number                                                 int64
feed_time_utc                                 datetime64[ns, UTC]
PlayerId                                                   object
Skill                                                       int64
PositionName                                               object
Value                                                     float64
TeamId                                                     object
FUllName                                                   object
DisplayName                                                object
IsActive                                                   object
DriverTLA                                                  object
OverallPpints                                              object
GamedayPoints                                              object
SelectedPercentage                                         object
CaptainSelectedPercentage                                  object
OldPlayerValue                                            float64
BestRaceFinished                                           object
HigestGridStart                                            object
HigestChampFinish                                          object
FastestPitstopAward                                        object
BestRaceFinishCount                                         int64
HighestGridStartCount                                       int64
HighestChampFinishCount                                     int64
FastestPitstopAwardCount                                    int64
QualifyingPoints                                           object
RacePoints                                                 object
SprintPoints                                               object
NoNegativePoints                                           object
F1PlayerId                                                 object
FirstName                                                  object
LastName                                                   object
SessionWisePoints                                          object
old_Value                                                 float64
new_value                                                 float64
ProjectedGamedayPoints                                     object
ProjectedNoNegativePoints                                  object
ProjectedOverallPpints                                     object
AdditionalStats.fastest_lap_pts                           float64
AdditionalStats.dotd_pts                                  float64
AdditionalStats.overtaking_pts                            float64
AdditionalStats.q3_finishes_pts                           float64
AdditionalStats.top10_race_position_pts                   float64
AdditionalStats.top8_sprint_position_pts                  float64
AdditionalStats.total_position_pts                        float64
AdditionalStats.total_position_gained_lost                float64
AdditionalStats.total_dnf_dq_pts                          float64
AdditionalStats.value_for_money                           float64
dtype: object

In [ ]:
# save the constructors dataframe as a CSV
csv_save_path = os.path.join("..", "..", "data", "processed", f"constructors_race_{race_number}.csv")
constructors_df.to_csv(csv_save_path)

In [ ]:
drivers_filter = df["PositionName"] == "DRIVER"
drivers_df = df[drivers_filter].copy()
drivers_df.head(2)

,race_number,feed_time_utc,PlayerId,Skill,PositionName,Value,TeamId,FUllName,DisplayName,TeamName,...,AdditionalStats.fastest_lap_pts,AdditionalStats.dotd_pts,AdditionalStats.overtaking_pts,AdditionalStats.q3_finishes_pts,AdditionalStats.top10_race_position_pts,AdditionalStats.top8_sprint_position_pts,AdditionalStats.total_position_pts,AdditionalStats.total_position_gained_lost,AdditionalStats.total_dnf_dq_pts,AdditionalStats.value_for_money
0,5,2026-05-19 15:14:29+00:00,18,1,DRIVER,12.8,23,Pierre Gasly,P. Gasly,Alpine,...,0.0,0.0,28.0,10.0,15.0,1.0,26.0,3.0,-20.0,0.72
1,5,2026-05-19 15:14:29+00:00,11059,1,DRIVER,8.2,23,Franco Colapinto,F. Colapinto,Alpine,...,0.0,0.0,27.0,3.0,7.0,0.0,10.0,4.0,0.0,1.25

In [42]:
drivers_df.columns[(drivers_df == "").all()]

Index(['HigestChampFinish', 'FastestPitstopAward', 'QualifyingPoints',
       'RacePoints', 'SprintPoints', 'NoNegativePoints'],
      dtype='object')

In [4]:
# Improving date check logic for fetching assets

import os
import pandas as pd
from datetime import date

races_csv = os.path.join("..", "..", "data", "reference", "races_2026.csv")
races = pd.read_csv(races_csv)
races["race_date"] = pd.to_datetime(races["race_date"]).dt.date

today = date.today()

completed_races = races[races["race_date"] <= today]
completed_races

,season,race_number,race_name,country,city_or_location,circuit_name,weekend_start_date,weekend_end_date,race_date,sprint_weekend
0,2026,1,Australian Grand Prix,Australia,Melbourne,Albert Park Circuit,2026-03-06,2026-03-08,2026-03-08,False
1,2026,2,Chinese Grand Prix,China,Shanghai,Shanghai International Circuit,2026-03-13,2026-03-15,2026-03-15,True
2,2026,3,Japanese Grand Prix,Japan,Suzuka,Suzuka Circuit,2026-03-27,2026-03-29,2026-03-29,False
3,2026,4,Miami Grand Prix,United States,Miami Gardens,Miami International Autodrome,2026-05-01,2026-05-03,2026-05-03,True

In [5]:
completed_races["race_number"].sort_values().tolist()

[1, 2, 3, 4]